[package]
name = "optima-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
optima-macros = {path ="../optima-macros"}
chrono = "0.4.19"

[profile.dev]
debug = 2
strip = "none"